config/routes.rb
Kinggordo::Application.routes.draw do
  
  

  resources :participants

  resources :currencies

  resources :sounds

  resources :colors

  devise_for :users

  get 'films/autocomplete_function_name'
  get 'films/autocomplete_person_name'
  get 'films/autocomplete_film_country'
  get 'films/autocomplete_film_company'
  get 'films/autocomplete_film_color'
  get 'films/autocomplete_film_sound'
  get 'films/autocomplete_film_producer'
  get 'films/all'
  
  
  
 
  
  resources :offices
  resources :users
  resources :salles
  resources :villes
  resources :functions
  resources :people 
  
  

  resources :films  do 
    resources :users
    
    resources :functions do
      resources :people
    end
    
    resources :salles do 
      resources :villes
    end
    
    get :autocomplete_film_name, :on => :collection

  end

  root :to => "Home#index"
  match 'user' => 'films#index', :as => :user_root
  

end

app/models/office.rb
class Office < ActiveRecord::Base
  
  def self.search(search)
    if search
      where('LOWER(titre) LIKE :search OR LOWER(titreo) LIKE :search OR LOWER(rea) LIKE :search OR LOWER(year) LIKE :search OR LOWER(country) LIKE :search OR LOWER(dure) LIKE :search OR LOWER(son) LIKE :search OR LOWER(producer) LIKE :search OR LOWER(lieu) LIKE :search OR LOWER(format) LIKE :search OR LOWER(support) LIKE :search OR LOWER(genre) LIKE :search OR LOWER(themea) LIKE :search OR LOWER(themeb) LIKE :search OR LOWER(note) LIKE :search', 
            { :search => "%#{search}%" })
    else
      scoped
    end
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_filter :authenticate_user!
  helper_method :sort_column, :sort_direction
  # GET /offices
  # GET /offices.xml
  def index
    found_offices = Office.search(params[:search])
    @count = found_offices.count

    @countries = Office.all.collect { |office| office.country }.compact.sort{ |a,b| a.downcase <=> b.downcase }.uniq
    found_offices = found_offices.where('country = ?', params[:country]) unless params[:country].blank?

    @sons = Office.all.collect { |office| office.son }.compact.sort{ |a,b| a.downcase <=> b.downcase }.uniq
    found_offices = found_offices.where('son = ?', params[:son]) unless params[:son].blank?

    @producers = Office.all.collect { |office| office.producer }.compact.sort{ |a,b| a.downcase <=> b.downcase }.uniq
    found_offices = found_offices.where('producer = ?', params[:producer]) unless params[:producer].blank?

    @lieux = Office.all.collect { |office| office.lieu }.compact.sort{ |a,b| a.downcase <=> b.downcase }.uniq
    found_offices = found_offices.where('lieu = ?', params[:lieu]) unless params[:lieu].blank?

    @lesformats = Office.all.collect { |office| office.format }.compact.sort{ |a,b| a.downcase <=> b.downcase }.uniq
    found_offices = found_offices.where('format = ?', params[:leformat]) unless params[:leformat].blank?

    @genres = Office.all.collect { |office| office.genre }.compact.sort{ |a,b| a.downcase <=> b.downcase }.uniq
    found_offices = found_offices.where('genre = ?', params[:genre]) unless params[:genre].blank?

    @supports = Office.all.collect { |office| office.support}.compact.sort{ |a,b| a.downcase <=> b.downcase }.uniq
    found_offices = found_offices.where('support = ?', params[:support]) unless params[:support].blank?

    @themeas = Office.all.collect { |office| office.themea}.compact.sort{ |a,b| a.downcase <=> b.downcase }.uniq
    found_offices = found_offices.where('themea = ?', params[:themea]) unless params[:themea].blank?

    @themebs = Office.all.collect { |office| office.themeb}.compact.sort{ |a,b| a.downcase <=> b.downcase }.uniq
    found_offices = found_offices.where('themeb = ?', params[:themeb]) unless params[:themeb].blank?

    @offices = found_offices.order(sort_column + " " + sort_direction).paginate(:per_page => 25, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @offices }
    end
  end

  # GET /offices/1
  # GET /offices/1.xml
  def show
    @office = Office.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @office }
    end
  end

  # GET /offices/new
  # GET /offices/new.xml
  def new
    @office = Office.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @office }
    end
  end

  # GET /offices/1/edit
  def edit
    @office = Office.find(params[:id])
  end

  # POST /offices
  # POST /offices.xml
  def create
    @office = Office.new(params[:office])

    respond_to do |format|
      if @office.save
        format.html { redirect_to(@office, :notice => 'Office was successfully created.') }
        format.xml  { render :xml => @office, :status => :created, :location => @office }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @office.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /offices/1
  # PUT /offices/1.xml
  def update
    @office = Office.find(params[:id])

    respond_to do |format|
      if @office.update_attributes(params[:office])
        format.html { redirect_to(@office, :notice => 'Office was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @office.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.xml
  def destroy
    @office = Office.find(params[:id])
    @office.destroy

    respond_to do |format|
      format.html { redirect_to(offices_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def sort_column
    Office.column_names.include?(params[:sort]) ? params[:sort] : "titre"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<%= form_for(@office) do |f| %>
<div id="Left">
  
  <div id="Right">    

    <div class="submit"><%= f.submit "Update Office",:class => "submit"%></div>


  </div>
  
  
  
  <% if @office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
      <% @office.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    TITRE:<br />
    <%= f.text_field :titre, :style =>"width:99%" %>
  </div>
  <div class="field">
    TITRE ORIGINAL ou ALTERNATIF:<br />
    <%= f.text_field :titreo, :style =>"width:99%" %>
  </div>
  <div class="field">
    REALISATEUR:<br />
    <%= f.text_field :rea, :style =>"width:99%" %>
  </div>
  <div class="field">
    ANNEE:<br />
    <%= f.text_field :year, :style =>"width:99%" %>
  </div>
  <div class="field">
    PAYS:<br />
    <%= f.text_field :country, :style =>"width:99%" %>
  </div>
  <div class="field">
    METRAGE APPROXIMATIF:<br />
    <%= f.text_field :dure, :style =>"width:99%" %>
  </div>
  <div class="field">
    SON:<br />
    <%= f.text_field :son, :style =>"width:99%" %>
  </div>
  <div class="field">
    PRODUCTEUR/DISTRIBUTEUR:<br />
    <%= f.text_field :producer, :style =>"width:99%" %>
  </div>
  <div class="field">
    LIEU OFFICE:<br />
    <%= f.text_field :lieu, :style =>"width:99%" %>
  </div>
  <div class="field">
    FORMAT EN MM:<br />
    <%= f.text_field :format, :style =>"width:99%" %>
  </div>
  <div class="field">
    SUPPORT:<br />
    <%= f.text_field :support, :style =>"width:99%" %>
  </div>
  <div class="field">
    GENRE:<br />
    <%= f.text_field :genre, :style =>"width:99%" %>
  </div>
  <div class="field">
    THEME 1<br />
    <%= f.text_field :themea, :style =>"width:99%" %>
  </div>
  <div class="field">
    THEME 2<br />
    <%= f.text_field :themeb, :style =>"width:99%" %>
  </div>
  <div class="field">
    NOTES<br />
    <%= f.text_area :note, :style =>"width:99%" %>
  </div>
  
<% end %>
</div>

app/views/offices/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<div id="Left">
  
  <div id="Right">    
    <div class="submit"><%= link_to 'Add Office', new_office_path, :class=>"submit" %></div>
    
  </div>


  <%= form_tag offices_path, :method => 'get', :id => "offices_search" do %>
<div id='recherche'>
  <span class="re">RECHERCHE</span>
   
      <%= text_field_tag :search, params[:search],:style =>"width:760px;"  %>
	<span><%= image_submit_tag "ldh_recherche_icone.jpg"%></span>
 <p>PAYS: <%= select_tag( "country", options_for_select( @countries, params[:country] ), :include_blank => true ) %>
	PRODUCTEUR/DISTRIBUTEUR: <%= select_tag( "producer", options_for_select( @producers, params[:producer] ), :include_blank => true ) %></p>
 <p>SON: <%= select_tag( "son", options_for_select( @sons, params[:son] ), :include_blank => true ) %>
    LIEU: <%= select_tag( "lieu", options_for_select( @lieux, params[:lieu] ), :include_blank => true ) %>
    FORMAT: <%= select_tag( "leformat", options_for_select( @lesformats, params[:leformat] ), :include_blank => true ) %>
    GENRE: <%= select_tag( "genre", options_for_select( @genres, params[:genre] ), :include_blank => true ) %>
    SUPPORT: <%= select_tag( "support", options_for_select( @supports, params[:support] ), :include_blank => true ) %></p>
 <p>THEME 1: <%= select_tag( "themea", options_for_select( @themeas, params[:themea] ), :include_blank => true ) %>
    THEME 2: <%= select_tag( "themeb", options_for_select( @themebs, params[:themeb] ), :include_blank => true ) %></p>
      - <%= link_to image_tag("ldh_recherche_fermeture.jpg"), offices_path %>

</div>
<div id="hr"></div>
    <div id="officessearchs"><%= render 'officessearchs' %></div>
  <% end %>




</div>

app/views/offices/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', offices_path %>

app/views/offices/show.html.erb
<div id="Left">
   
  <div id="Right">    
    <div class="submit"><%= link_to 'Edit Office ', edit_office_path(@office), :class=>"submit" %></div>
  </div>

<p>
  <b>TITRE:</b>
  <%= @office.titre %>
</p>

<p>
  <b>TITRE ORIGINAL ou ALTERNATIF:</b>
  <%= @office.titreo %>
</p>

<p>
  <b>REALISATEUR:</b>
  <%= @office.rea %>
</p>

<p>
  <b>ANNEE:</b>
  <%= @office.year %>
</p>

<p>
  <b>PAYS:</b>
  <%= @office.country %>
</p>

<p>
  <b>METRAGE APPROXIMATIF:</b>
  <%= @office.dure %>
</p>

<p>
  <b>SON:</b>
  <%= @office.son %>
</p>

<p>
  <b>PRODUCTEUR/DISTRIBUTEUR:</b>
  <%= @office.producer %>
</p>

<p>
  <b>LIEU OFFICE:</b>
  <%= @office.lieu %>
</p>

<p>
  <b>FORMAT EN MM:</b>
  <%= @office.format %>
</p>

<p>
  <b>SUPPORT:</b>
  <%= @office.support %>
</p>

<p>
  <b>GENRE:</b>
  <%= @office.genre %>
</p>

<p>
  <b>THEME 1:</b>
  <%= @office.themea %>
</p>

<p>
  <b>THEME 2:</b>
  <%= @office.themeb %>
</p>

<p>
  <b>NOTES:</b>
  <%= @office.note %>
</p>

<br/>
<br/>

</div>