config/routes.rb
Kinggordo::Application.routes.draw do
  
  

  resources :participants

  resources :currencies

  resources :sounds

  resources :colors

  devise_for :users

  get 'films/autocomplete_function_name'
  get 'films/autocomplete_person_name'
  get 'films/autocomplete_film_country'
  get 'films/autocomplete_film_company'
  get 'films/autocomplete_film_color'
  get 'films/autocomplete_film_sound'
  get 'films/autocomplete_film_producer'
  get 'films/all'
  
  
  
 
  
  resources :offices
  resources :users
  resources :salles
  resources :villes
  resources :functions
  resources :people 
  
  

  resources :films  do 
    resources :users
    
    resources :functions do
      resources :people
    end
    
    resources :salles do 
      resources :villes
    end
    
    get :autocomplete_film_name, :on => :collection

  end

  root :to => "Home#index"
  match 'user' => 'films#index', :as => :user_root
  

end

app/models/currency.rb
class Currency < ActiveRecord::Base
  has_many :joints
  has_many :salles
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  # GET /currencies
  # GET /currencies.xml
  def index
    @currencies = Currency.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @currencies }
    end
  end

  # GET /currencies/1
  # GET /currencies/1.xml
  def show
    @currency = Currency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @currency }
    end
  end

  # GET /currencies/new
  # GET /currencies/new.xml
  def new
    @currency = Currency.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @currency }
    end
  end

  # GET /currencies/1/edit
  def edit
    @currency = Currency.find(params[:id])
  end

  # POST /currencies
  # POST /currencies.xml
  def create
    @currency = Currency.new(params[:currency])

    respond_to do |format|
      if @currency.save
        format.html { redirect_to(@currency, :notice => 'Currency was successfully created.') }
        format.xml  { render :xml => @currency, :status => :created, :location => @currency }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @currency.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /currencies/1
  # PUT /currencies/1.xml
  def update
    @currency = Currency.find(params[:id])

    respond_to do |format|
      if @currency.update_attributes(params[:currency])
        format.html { redirect_to(@currency, :notice => 'Currency was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @currency.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.xml
  def destroy
    @currency = Currency.find(params[:id])
    @currency.destroy

    respond_to do |format|
      format.html { redirect_to(currencies_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.erb
<%= form_for(@currency) do |f| %>
 	<label for="first_name">currency</label>
	     <%= f.text_field :name, :style =>"width:20%" %>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/currencies/edit.html.erb
<h1>Editing currency</h1>

<%= render 'form' %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<h1>Listing currencies</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @currencies.each do |currency| %>
  <tr>
    <td><%= link_to 'Show', currency %></td>
    <td><%= link_to 'Edit', edit_currency_path(currency) %></td>
    <td><%= link_to 'Destroy', currency, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Currency', new_currency_path %>

app/views/currencies/new.html.erb
<h1>New currency</h1>

<%= render 'form' %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_currency_path(@currency) %> |
<%= link_to 'Back', currencies_path %>