config/routes.rb
Kinggordo::Application.routes.draw do
  
  

  resources :participants

  resources :currencies

  resources :sounds

  resources :colors

  devise_for :users

  get 'films/autocomplete_function_name'
  get 'films/autocomplete_person_name'
  get 'films/autocomplete_film_country'
  get 'films/autocomplete_film_company'
  get 'films/autocomplete_film_color'
  get 'films/autocomplete_film_sound'
  get 'films/autocomplete_film_producer'
  get 'films/all'
  
  
  
 
  
  resources :offices
  resources :users
  resources :salles
  resources :villes
  resources :functions
  resources :people 
  
  

  resources :films  do 
    resources :users
    
    resources :functions do
      resources :people
    end
    
    resources :salles do 
      resources :villes
    end
    
    get :autocomplete_film_name, :on => :collection

  end

  root :to => "Home#index"
  match 'user' => 'films#index', :as => :user_root
  

end

app/models/participant.rb
class Participant < ActiveRecord::Base
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  # GET /participants
  # GET /participants.xml
  def index
    @participants = Participant.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @participants }
    end
  end

  # GET /participants/1
  # GET /participants/1.xml
  def show
    @participant = Participant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @participant }
    end
  end

  # GET /participants/new
  # GET /participants/new.xml
  def new
    @participant = Participant.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @participant }
    end
  end

  # GET /participants/1/edit
  def edit
    @participant = Participant.find(params[:id])
  end

  # POST /participants
  # POST /participants.xml
  def create
    @participant = Participant.new(params[:participant])

    respond_to do |format|
      if @participant.save
        format.html { redirect_to(@participant, :notice => 'Participant was successfully created.') }
        format.xml  { render :xml => @participant, :status => :created, :location => @participant }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @participant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /participants/1
  # PUT /participants/1.xml
  def update
    @participant = Participant.find(params[:id])

    respond_to do |format|
      if @participant.update_attributes(params[:participant])
        format.html { redirect_to(@participant, :notice => 'Participant was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @participant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.xml
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to(participants_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
<label for="first_name">Name</label><br/ >
<%=  f.text_field :name, :style =>"width:80%" %>
<br/ >
<label for="first_name">Mail</label><br/ >
<%=  f.text_field :mail, :style =>"width:80%" %>
<br/ >
<label for="first_name">Web</label><br/ >
<%=  f.text_field :web, :style =>"width:80%" %>
<br/ >
<label for="first_name">Comment</label><br/ >
<%=  f.text_area :body, :style =>"width:80%" %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>

	
      </ul>




    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<br/>
<h1>Listing participants</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @participants.each do |participant| %>

  <tr>
	<td><%= participant.name%></td>
    
    <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
    <td><%= link_to 'Destroy', participant, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<br/ >
<h1>New participant</h1>
<br/ >
<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>